services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
    ports:
      - "6434:5432"
    networks:
      - rag-net
  
  ollama:
    build: .
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - rag-net


  rag-app:
    build: ./rag-app
    ports:
      - "8044:8044"
    networks:
      - rag-net
    depends_on:
      - timescaledb
      - ollama
    environment:
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/postgres
      - OLLAMA_URL=http://ollama:11434
      - INGEST_API_KEY=${INGEST_API_KEY}

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open_webui_data:/app/backend/data
    ports:
      - "8080:8080"
    networks:
      - rag-net

networks:
  rag-net:
    name: ollama-rag-net

volumes:
  timescale_data:
  ollama_data:
  open_webui_data:
